packages: []

catalog:
  '@types/hosted-git-info': ^3.0.5
  '@types/node': ^25.0.3
  hosted-git-info: ^9.0.2
  ky: ^1.14.2
  typescript: ^5.9.3

catalogs:
  cli:
    '@sxzz/create': ^0.15.6
    monoman: ^0.8.0
    node-modules-inspector: ^1.2.0
    stale-dep: ^0.8.4
    tsdown: ^0.19.0-beta.1
    unloader: ^0.8.3
    vite-hyper-config: ^0.8.1
  libs:
    '@quansync/fs': ^1.0.0
    '@sxzz/test-utils': ^0.5.15
    '@vue/babel-plugin-jsx': ^2.0.1
    '@vue/repl': ^4.7.1
    ast-kit: ^2.2.0
    ast-walker-scope: ^0.8.3
    dts-resolver: ^2.1.3
    import-without-cache: ^0.2.5
    magic-string-ast: ^1.0.3
    obug: ^2.1.1
    pnpm-multi-versions: ^0.5.4
    quansync: ^1.0.0
    rolldown-plugin-dts: ^0.20.0
    rolldown-plugin-dts-snapshot: ^0.3.2
    rolldown-plugin-require-cjs: ^0.3.3
    rolldown-plugin-wasm: ^0.2.1
    rolldown-string: ^0.2.1
    tc39-throw: ^0.2.1
    tc39-try: ^0.4.3
    tsdown-preset-sxzz: ^0.2.0
    tsgo-wasm: ^2026.1.2
    untsx: ^0.1.3
  lint:
    '@sxzz/eslint-config': ^7.4.4
    '@sxzz/prettier-config': ^2.2.6
    eslint: ^9.39.2
    eslint-plugin-importer: ^0.2.1
    eslint-plugin-sxzz: ^0.4.2
    prettier: ^3.7.4
  unplugin:
    unplugin: ^2.3.11
    unplugin-ast: ^0.15.4
    unplugin-combine: ^2.2.0
    unplugin-inline-enum: ^0.6.4
    unplugin-isolated-decl: ^0.15.7
    unplugin-jsx-string: ^0.10.0
    unplugin-lightningcss: ^0.4.4
    unplugin-macros: ^0.18.6
    unplugin-oxc: ^0.5.7
    unplugin-quansync: ^0.5.1
    unplugin-raw: ^0.6.3
    unplugin-replace: ^0.6.3
    unplugin-unused: ^0.5.6
    unplugin-utils: ^0.3.1
    unplugin-vue: ^7.1.0
    unplugin-vue-jsx: ^0.8.1
    unplugin-vue-named-export: ^0.9.3
  vue:
    '@vue-macros/common': ^3.1.1
    vue-functional-ref: ^0.7.2
    vue-macros: ^3.1.1
    vue-simple-props: ^0.6.3

allowBuilds:
  esbuild: false

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
