packages: []

catalog:
  '@types/node': ^22.13.9

catalogs:
  cli:
    '@sxzz/create': ^0.14.3
    monoman: ^0.6.7
    node-modules-inspector: ^0.3.0
    stale-dep: ^0.8.1
    tsdown: ^0.6.4
    unloader: ^0.3.0
    vite-hyper-config: ^0.6.1

  libs:
    '@quansync/fs': ^0.1.1
    '@sxzz/test-utils': ^0.5.1
    ast-kit: ^1.4.2
    ast-walker-scope: ^0.7.1
    gh-apis: ^0.2.1
    magic-string-ast: ^0.8.0
    pnpm-multi-versions: ^0.4.1
    quansync: ^0.2.8
    unws: ^0.3.0

  lint:
    '@sxzz/eslint-config': ^5.2.0
    '@sxzz/prettier-config': ^2.2.1
    eslint: ^9.21.0
    eslint-plugin-pnpm: ^0.1.0
    eslint-plugin-sxzz: ^0.2.1
    prettier: ^3.5.3

  unplugin:
    unplugin: ^2.2.0
    unplugin-ast: ^0.14.2
    unplugin-combine: ^1.2.1
    unplugin-inline-enum: ^0.3.1
    unplugin-isolated-decl: ^0.13.2
    unplugin-jsx-string: ^0.9.1
    unplugin-lightningcss: ^0.3.2
    unplugin-macros: ^0.16.1
    unplugin-oxc: ^0.2.7
    unplugin-quansync: ^0.3.4
    unplugin-raw: ^0.4.4
    unplugin-replace: ^0.5.1
    unplugin-unused: ^0.4.3
    unplugin-utils: ^0.2.4
    unplugin-vue: ^6.0.1
    unplugin-vue-jsx: ^0.6.1
    unplugin-vue-named-export: ^0.7.2

  vue:
    '@vue-macros/common': ^3.0.0-beta.3
    vtom: ^1.2.1
    vue-functional-ref: ^0.6.2
    vue-macros: ^3.0.0-beta.3
    vue-simple-props: ^0.5.5
