packages: []

catalog:
  '@types/hosted-git-info': ^3.0.5
  '@types/node': ^24.3.0
  hosted-git-info: ^9.0.0

catalogs:
  cli:
    '@sxzz/create': ^0.15.3
    monoman: ^0.7.2
    node-modules-inspector: ^1.1.1
    stale-dep: ^0.8.3
    tsdown: ^0.14.2
    tsgo-dev: ^2025.8.26
    unloader: ^0.5.0
    unotp: ^0.1.0
    vite-hyper-config: ^0.7.1

  libs:
    '@quansync/fs': ^0.1.5
    '@sxzz/test-utils': ^0.5.10
    '@vue/babel-plugin-jsx': ^1.5.0
    '@vue/repl': ^4.6.3
    ast-kit: ^2.1.2
    ast-walker-scope: ^0.8.2
    dts-resolver: ^2.1.2
    gh-apis: ^0.2.2
    magic-string-ast: ^1.0.2
    pnpm-multi-versions: ^0.5.2
    quansync: ^0.2.11
    rolldown-plugin-dts: ^0.15.9
    tc39-throw: ^0.2.0
    tc39-try: ^0.4.2
    tsgo-wasm: ^2025.8.26
    untsx: ^0.1.2

  lint:
    '@sxzz/eslint-config': ^7.1.4
    '@sxzz/prettier-config': ^2.2.4
    eslint: ^9.34.0
    eslint-plugin-sxzz: ^0.4.1
    prettier: ^3.6.2

  unplugin:
    unplugin: ^2.3.8
    unplugin-ast: ^0.15.2
    unplugin-combine: ^2.1.2
    unplugin-inline-enum: ^0.4.1
    unplugin-isolated-decl: ^0.15.1
    unplugin-jsx-string: ^0.9.1
    unplugin-lightningcss: ^0.4.2
    unplugin-macros: ^0.18.0
    unplugin-oxc: ^0.5.1
    unplugin-quansync: ^0.4.4
    unplugin-raw: ^0.6.1
    unplugin-replace: ^0.6.1
    unplugin-unused: ^0.5.2
    unplugin-utils: ^0.3.0
    unplugin-vue: ^7.0.1
    unplugin-vue-named-export: ^0.9.1

  vue:
    '@vue-macros/common': ^3.0.0-beta.21
    vtom: ^2.0.0
    vue-functional-ref: ^0.7.2
    vue-macros: ^3.0.0-beta.21
    vue-simple-props: ^0.6.2
