packages: []

catalog:
  '@types/hosted-git-info': ^3.0.5
  '@types/node': ^24.9.1
  hosted-git-info: ^9.0.2

catalogs:
  cli:
    '@sxzz/create': ^0.15.4
    monoman: ^0.7.3
    node-modules-inspector: ^1.2.0
    stale-dep: ^0.8.4
    tsdown: ^0.15.9
    tsgo-dev: ^2025.10.26
    unloader: ^0.5.0
    unotp: ^0.1.0
    vite-hyper-config: ^0.7.1

  libs:
    '@quansync/fs': ^0.1.5
    '@sxzz/test-utils': ^0.5.12
    '@vue/babel-plugin-jsx': ^2.0.1
    '@vue/repl': ^4.7.0
    ast-kit: ^2.1.3
    ast-walker-scope: ^0.8.3
    dts-resolver: ^2.1.2
    gh-apis: ^0.2.2
    magic-string-ast: ^1.0.3
    pnpm-multi-versions: ^0.5.3
    quansync: ^0.2.11
    rolldown-plugin-dts: ^0.17.1
    rolldown-plugin-require-cjs: ^0.3.1
    tc39-throw: ^0.2.1
    tc39-try: ^0.4.3
    tsgo-wasm: ^2025.10.26
    untsx: ^0.1.2

  lint:
    '@sxzz/eslint-config': ^7.2.7
    '@sxzz/prettier-config': ^2.2.4
    eslint: ^9.38.0
    eslint-plugin-sxzz: ^0.4.1
    prettier: ^3.6.2

  unplugin:
    unplugin: ^2.3.10
    unplugin-ast: ^0.15.3
    unplugin-combine: ^2.1.3
    unplugin-inline-enum: ^0.6.2
    unplugin-isolated-decl: ^0.15.3
    unplugin-jsx-string: ^0.10.0
    unplugin-lightningcss: ^0.4.3
    unplugin-macros: ^0.18.2
    unplugin-oxc: ^0.5.3
    unplugin-quansync: ^0.4.5
    unplugin-raw: ^0.6.3
    unplugin-replace: ^0.6.2
    unplugin-unused: ^0.5.4
    unplugin-utils: ^0.3.1
    unplugin-vue: ^7.0.3
    unplugin-vue-jsx: ^0.8.1
    unplugin-vue-named-export: ^0.9.1

  vue:
    '@vue-macros/common': ^3.1.1
    vue-functional-ref: ^0.7.2
    vue-macros: ^3.1.1
    vue-simple-props: ^0.6.3
