catalog:
  '@types/node': ^24.0.15

catalogs:
  cli:
    '@sxzz/create': ^0.15.1
    monoman: ^0.7.1
    node-modules-inspector: ^1.0.0
    stale-dep: ^0.8.2
    tsdown: ^0.13.0-beta.2
    tsgo-dev: ^2025.7.19
    unloader: ^0.4.5
    vite-hyper-config: ^0.7.0

  libs:
    '@quansync/fs': ^0.1.3
    '@sxzz/test-utils': ^0.5.7
    '@vue/babel-plugin-jsx': ^1.4.0
    '@vue/repl': ^4.6.2
    ast-kit: ^2.1.1
    ast-walker-scope: ^0.8.1
    dts-resolver: ^2.1.1
    gh-apis: ^0.2.2
    magic-string-ast: ^1.0.0
    pnpm-multi-versions: ^0.5.1
    quansync: ^0.2.10
    rolldown-plugin-dts: ^0.14.1
    tsgo-wasm: ^2025.7.19
    unws: ^0.3.2

  lint:
    '@sxzz/eslint-config': ^7.0.6
    '@sxzz/prettier-config': ^2.2.3
    eslint: ^9.31.0
    eslint-plugin-sxzz: ^0.4.0
    prettier: ^3.6.2

  unplugin:
    unplugin: ^2.3.5
    unplugin-ast: ^0.15.1
    unplugin-combine: ^2.0.0
    unplugin-inline-enum: ^0.4.1
    unplugin-isolated-decl: ^0.14.5
    unplugin-jsx-string: ^0.9.1
    unplugin-lightningcss: ^0.4.1
    unplugin-macros: ^0.17.1
    unplugin-oxc: ^0.4.6
    unplugin-quansync: ^0.4.3
    unplugin-raw: ^0.5.0
    unplugin-replace: ^0.6.0
    unplugin-unused: ^0.5.1
    unplugin-utils: ^0.2.4
    unplugin-vue: ^7.0.0
    unplugin-vue-jsx: ^0.6.1
    unplugin-vue-named-export: ^0.9.0

  vue:
    '@vue-macros/common': ^3.0.0-beta.17
    vtom: ^2.0.0
    vue-functional-ref: ^0.7.0
    vue-macros: ^3.0.0-beta.17
    vue-simple-props: ^0.6.2
