name: Update Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@v1
        with:
          persist-credentials: true

      - name: Update
        run: node ./stats.ts

      - name: Commit
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: update stats [ci skip]'
          add: stats.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
