name: Update Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@main
        with:
          persist-credentials: true

      - name: Update
        run: node ./stats.ts

      - name: Commit
        uses: EndBug/add-and-commit@645ecc0dd0a57f4d86d26c0aa5fc42c0a856fbca # v11.0.0
        with:
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: update stats [ci skip]'
          add: stats.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
